# Generated by Django 4.2.1 on 2023-06-04 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='Сумма транзакции')),
                ('created', models.DateTimeField(verbose_name='Дата транзакции')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Добавление',
                'verbose_name_plural': 'Добавления',
            },
        ),
        migrations.DeleteModel(
            name='Additions',
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'Добавление', 'verbose_name_plural': 'Добавления'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Добавление', 'verbose_name_plural': 'Добавления'},
        ),
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Добавление', 'verbose_name_plural': 'Добавления'},
        ),
        migrations.AddField(
            model_name='history',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='Сумма транзакции'),
        ),
        migrations.AddField(
            model_name='history',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='profile',
            name='amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Сумма транзакции'),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statistics',
            name='amount',
            field=models.PositiveIntegerField(null=True, verbose_name='Сумма транзакции'),
        ),
        migrations.AddField(
            model_name='statistics',
            name='title',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
