# Generated by Django 4.2 on 2023-05-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_transactions_delete_additions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.CharField(default='income', max_length=255),
        ),
    ]
